{
 "title": "EII TDengine Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Summary",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select count(*)  'Total  temperature  data points' from eiidemo.point_data"
    },
    {
     "formatType": "Time series",
     "sql": "select count(*) 'Total voltage data points' from eiidemo.electric_meter"
    }
   ]
  },
  {
   "title": "Temperature data points collected from MQTT Publisher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select min(temperature) from eiidemo.point_data interval(5s)"
    },
    {
     "formatType": "Time series",
     "sql": "select max(temperature) from eiidemo.point_data interval(5s)"
    },
    {
     "formatType": "Time series",
     "sql": "select avg(temperature) from eiidemo.point_data interval(30s)"
    }
   ]
  },
  {
   "title": "Electric voltage data points collected from EMB publisher",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select avg(value)  'avg voltage' from eiidemo.electric_meter where device_id='BJ-12345' and metric_type='voltage' interval(5s)"
    },
    {
     "formatType": "Time series",
     "sql": "select max(value)  'max voltage' from eiidemo.electric_meter where device_id='BJ-12345' and metric_type='voltage' interval(5s)"
    }
   ]
  }
 ]
}