kind: pipeline
name: default

steps:
- name: test
  image: golang
  commands:
  - wget https://www.taosdata.com/assets-download/TDengine-server-2.1.7.2-beta-Linux-x64.tar.gz
  - tar xvf TDengine-server-2.1.7.2-beta-Linux-x64.tar.gz
  - cd TDengine-server-2.1.7.2/
  - printf "\n\n"|./install.sh
  - nohup taosd &
  - cd ../
  - go mod tidy
  - go test -v ./...
