{
 "title": "EII TDengine Demo",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Summary",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select temperature from eiidemo.point_data",
     "timeshift": {
      "period": null
     }
    },
    {
     "formatType": "Time series",
     "sql": "select humidity from eiidemo.point_data",
     "timeshift": {
      "period": null
     }
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 9, "x": 3, "y": 0 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select min(temperature) from eiidemo.point_data interval(5s)"
    },
    {
     "formatType": "Time series",
     "sql": "select avg(temperature) from eiidemo.point_data interval(30s)"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 12, "y": 0 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select min(humidity) from eiidemo.point_data interval(5s)",
     "timeshift": {
      "period": null
     }
    },
    {
     "formatType": "Time series",
     "sql": "select avg(humidity) from eiidemo.point_data interval(60s)",
     "timeshift": { "period": 5 }
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select avg(pressure) from eiidemo.point_data interval(10s)",
     "timeshift": {
      "period": null
     }
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 10, "x": 12, "y": 12 },
   "targets": [
    {
     "formatType": "Time series",
     "sql": "select avg(value)  'avg voltage' from eiidemo.electric_meter where device_id='BJ-12345' and metric_type='voltage' interval(5s)"
    },
    {
     "formatType": "Time series",
     "sql": "select max(value)  'max voltage' from eiidemo.electric_meter where device_id='BJ-12345' and metric_type='voltage' interval(5s)"
    }
   ]
  }
 ]
}